all: p1 question1 question2 question3 question4 question5 question6 question7 question8
 
clean:
	rm -f ./dist/*

p1: p1.c
	gcc -o ./dist/p1 p1.c -Wall

question1:
	gcc -o ./dist/question1 question1.c -Wall

question2:
	gcc -o ./dist/question2 question2.c -Wall

question3:
	gcc -o ./dist/question3 question3.c -Wall

question4:
	gcc -o ./dist/question4 question4.c -Wall

question5:
	gcc -o ./dist/question5 question5.c -Wall

question6:
	gcc -o ./dist/question6 question6.c -Wall

question7:
	gcc -o ./dist/question7 question7.c -Wall

question8:
	gcc -o ./dist/question8 question8.c -Wall