all: p1 question1 question2 question3
 
clean:
	rm -f ./dist

p1: p1.c
	gcc -o ./dist/p1 p1.c -Wall

question1:
	gcc -o ./dist/question1 question1.c -Wall

question2:
	gcc -o ./dist/question2 question2.c -Wall

question3:
	gcc -o ./dist/question3 question3.c -Wall
